DESC BOFF.LGBRAND
DESC BOFF.LGPRODUCT
DESC BOFF.LGVENDOR
DESC BOFF.LGSUPPLIES
DESC BOFF.LGDEPARTMENT
DESC BOFF.LGEMPLOYEE
DESC BOFF.LGSALARY_HISTORY
DESC BOFF.LGCUSTOMER
DESC BOFF.LGINVOICE
DESC BOFF.LGLINE

/*1*/

SELECT COUNT(PROD_CATEGORY)
FROM BOFF.LGPRODUCT
GROUP BY PROD_CATEGORY
ORDER BY PROD_CATEGORY;


/*2*/

SELECT COUNT(INV_NUM), EMPLOYEE_ID
FROM BOFF.LGINVOICE
WHERE INV_DATE< TO_DATE('01-FEB-13','DD-MON-YY')
GROUP BY EMPLOYEE_ID
ORDER BY EMPLOYEE_ID;

/*3*/

SELECT COUNT(*) 
FROM BOFF.LGEMPLOYEE 
WHERE EMP_HIREDATE>=TO_DATE('01-01-1978','MM-DD-YYYY')
AND
EMP_HIREDATE<=TO_DATE('12-31-1990','MM-DD-YYYY');

/*4*/

SELECT PROD_SKU, PROD_PRICE
FROM BOFF.LGPRODUCT
WHERE PROD_BASE='Solvent'
AND PROD_CATEGORY= 'Top Coat'
AND PROD_PRICE>35;

/*5*/ 

SELECT BRAND_ID, SUM(PROD_QOH) AS TOTALINVENTORY
FROM BOFF.LGPRODUCT
GROUP BY BRAND_ID
ORDER BY BRAND_ID DESC;

/*6*/
COLUMN PROD_DESCRIPT FORMAT A75
SELECT PROD_DESCRIPT,
PROD_QOH,
PROD_PRICE,
TO_CHAR((PROD_QOH * PROD_PRICE), '$999,999.00') AS SUBTOTAL
FROM BOFF.LGPRODUCT 
WHERE PROD_QOH * PROD_PRICE>4000
ORDER BY SUBTOTAL;

/*7*/ 
SELECT TO_CHAR(SUM(PROD_QOH * PROD_PRICE), '$999,999,999.00') AS "TOTAL VALUE"
FROM BOFF.LGPRODUCT;

/*8*/
SELECT EMP_FNAME, EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
FROM BOFF.LGEMPLOYEE
WHERE DEPT_NUM = 600 OR EMP_TITLE = 'DRIVER'
ORDER BY EMP_LNAME, EMP_FNAME;

/*9*/
SELECT CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_BALANCE
FROM BOFF.LGCUSTOMER
WHERE CUST_CODE=1 OR CUST_CODE=10 OR CUST_CODE=100 OR CUST_CODE=1000
ORDER BY CUST_CODE;



/*10*/

SELECT TO_CHAR(SUM(CUST_BALANCE), '$999,999.00') AS "Total Balance", 
TO_CHAR(MIN(CUST_BALANCE), '$999,999.00') AS " Minimum Balance", 
TO_CHAR(MAX(CUST_BALANCE), '$999,999.00') AS "Maximum Balance",
TO_CHAR(AVG(CUST_BALANCE), '$999,999.00') AS "Average Balance"
FROM BOFF.LGCUSTOMER;
