/****** 1 *******/
DECLARE
	STUDENT_ID 	NUMBER(5):=10010;
	STUDENT_LNAME	VARCHAR2(10):= 'DaBook';
	STUDENT_FNAME	VARCHAR2(10):= 'Reed';
	STUDENT_NAME	VARCHAR2(21);
	CLUB_NAME	VARCHAR2(25):='Yard Sale Skimmers';
	DUES_AMT 	NUMBER(5):=100;
	STUDENT_MESSAGE	VARCHAR2(200);
BEGIN
	STUDENT_NAME:= (STUDENT_FNAME|| ' ' ||STUDENT_LNAME);
	STUDENT_MESSAGE:=('Student '||STUDENT_NAME||' still owes the '||CLUB_NAME|| ' club '||TO_CHAR(DUES_AMT, '$999.99')||'.');
	DBMS_OUTPUT.PUT_LINE(STUDENT_MESSAGE);
END;
/

/****** 2 *******/
DECLARE
	STUDENT_ID	NUMBER(5):= 10066;
	STUDENT_LNAME	VARCHAR2(10):= 'Derbox';
	STUDENT_FNAME	VARCHAR2(10):= 'Chad';
	STUDENT_NAME	VARCHAR2(21);
	CLUB_NAME	VARCHAR2(35):= 'Under-Water Basket Weavers';
	MEMBER_EXP_DATE		DATE:= TO_DATE('31-Oct-19','DD-Mon-YY');
	MEM_EXPIRE_MESSAGE	VARCHAR2(200);
BEGIN
	
	STUDENT_NAME:= (STUDENT_FNAME|| ' ' ||STUDENT_LNAME);
	MEM_EXPIRE_MESSAGE :=('The membership to '|| CLUB_NAME||' for student '||STUDENT_NAME||' will expire on '||TO_CHAR(MEMBER_EXP_DATE, 'FMMonth DD YYYY')||'.');
	DBMS_OUTPUT.PUT_LINE(MEM_EXPIRE_MESSAGE);
END;
/

/****** 3 *******/
DECLARE
	STUDENT_ID	NUMBER(5):=10033;
	STUDENT_LNAME	VARCHAR2(10):='UrPhone';
	STUDENT_FNAME	VARCHAR2(10):='Luce';
	STUDENT_NAME	VARCHAR2(21);
	PHONE_NUMBER	NUMBER(10):= 7248137545;
	PHONE1		VARCHAR2(5);
	PHONE2		VARCHAR2(15);
	CONTACT_MESSAGE	VARCHAR2(200);	
BEGIN
	PHONE1:= ('('||TO_CHAR(SUBSTR(PHONE_NUMBER, 1, 3))||')');
	PHONE2:=(' '||TO_CHAR(SUBSTR(PHONE_NUMBER, 4,3))||'-'||TO_CHAR(SUBSTR(PHONE_NUMBER, 7, 4)));
	STUDENT_NAME:= (STUDENT_FNAME|| ' ' ||STUDENT_LNAME);
	CONTACT_MESSAGE := (STUDENT_NAME||'''s contact number is' || PHONE1|| PHONE2 ||'.');
	DBMS_OUTPUT.PUT_LINE(CONTACT_MESSAGE);
END;
/

/****** 4 *******/
DECLARE
	STUDENT_ID	NUMBER(5):=10055;
	STUDENT_LNAME	VARCHAR2(10):= 'Hacker';
	STUDENT_FNAME	VARCHAR2(10):= 'Iza';
	STUDENT_NAME	VARCHAR2(21);
	CLUB_NAME	VARCHAR2(25):='Yard Sale Skiers';
	TODAY_DATE	DATE;
	MEMBER_EXPIRE_DATE	DATE:= TO_DATE('31-May-18', 'DD-Mon-YY');
	EXPIRE_MESSAGE	VARCHAR2(200);
BEGIN
	TODAY_DATE:=SYSDATE;
	STUDENT_NAME:= (STUDENT_FNAME|| ' ' ||STUDENT_LNAME);
	EXPIRE_MESSAGE:= ('On the date of '||
	TO_CHAR(TODAY_DATE, 'Month DD, YYYY')||	
	', the membership to '||CLUB_NAME||
	' for student '||STUDENT_NAME||
	' expired on '||
	TO_CHAR(MEMBER_EXPIRE_DATE, 'FMMonth DD, YYYY')||'.');
	DBMS_OUTPUT.PUT_LINE(EXPIRE_MESSAGE);
END;
/

/****** 5 *******/
DECLARE
	STUDENT_ID	NUMBER(5):=10044;
	TODAY_DATE	DATE;
	STUDENT_LNAME	VARCHAR2(10):='Eslee';
	STUDENT_FNAME	VARCHAR2(10):='Seerey';
	STUDENT_NAME	VARCHAR2(21);
	EXP_DATE	DATE:= TO_DATE('31-Dec-21', 'DD-Mon-YY');
	CLUB_NAME	VARCHAR2(25):='Yard Sale Skiers';
	PHONE_NUMBER	NUMBER(10):=3305149786;
	PHONE1		VARCHAR2(5);
	PHONE2		VARCHAR2(10);
	BIG_MESSAGE	VARCHAR2(400);
	AMT_DUE		NUMBER(9):= 75.75;

BEGIN
	PHONE1:= ('('||TO_CHAR(SUBSTR(PHONE_NUMBER, 1, 3))||')');
	PHONE2:=(' '||TO_CHAR(SUBSTR(PHONE_NUMBER, 4,3))||'-'||TO_CHAR(SUBSTR(PHONE_NUMBER, 7, 4)));
	TODAY_DATE:= SYSDATE;
	BIG_MESSAGE:=('On the date of '||TO_CHAR(TODAY_DATE, 'FMMonth DD, YYYY')||', the membership to '||CLUB_NAME||' for student '||STUDENT_NAME||' will expire on '||
	TO_CHAR(EXP_DATE, 'FMMonth DD, YYYY')||'.  This member can be contacted at '||PHONE1||PHONE2||' and notified that they still owe '
	|| TO_CHAR(AMT_DUE, '$999.99')||' in dues.');   
	DBMS_OUTPUT.PUT_LINE(BIG_MESSAGE);
END;
/
