/*1*/
DECLARE
	O_ID		NUMBER	:=	1;
	
	DISCOUNT_TOTAL	NUMBER	:=	0;
	ORIGINAL_TOTAL	NUMBER	:=	0;
	DISCOUNTED_TOTAL NUMBER	:=	0;
	TOTAL_DIF	NUMBER:=	0;
	CURSOR ORDER_CALC IS 
		SELECT SUM(OL_QUANTITY*INV_PRICE)
		FROM ORDER_LINE, INVENTORY, ORDERS
		WHERE ORDER_LINE.INV_ID=INVENTORY.INV_ID AND ORDERS.O_ID=ORDER_LINE.O_ID
		GROUP BY ORDERS.O_ID;
	ORDER_TOTAL	ORDERS.O_ID%TYPE;
BEGIN
    	OPEN ORDER_CALC;
	DBMS_OUTPUT.PUT_LINE('*****NEW DISCOUNT RESULTS*****');
	DBMS_OUTPUT.PUT_LINE(' ');
	LOOP 
     		FETCH ORDER_CALC INTO ORDER_TOTAL;
		EXIT WHEN ORDER_CALC%NOTFOUND;
		IF ORDER_TOTAL>200 THEN DISCOUNT_TOTAL:=(ORDER_TOTAL*.8);
		ELSIF ORDER_TOTAL>100 THEN DISCOUNT_TOTAL:=(ORDER_TOTAL*.9);
		ELSE DISCOUNT_TOTAL:=ORDER_TOTAL;
		END IF;
		DBMS_OUTPUT.PUT_LINE('Order #'||O_ID||'  Order Total:'||CHR(9)||TO_CHAR(ORDER_TOTAL,'$999.99')||'  Discounted Total:'||CHR(9)||
			TO_CHAR(DISCOUNT_TOTAL, '$999.99'));
 		O_ID:=O_ID+1;
		ORIGINAL_TOTAL:=ORIGINAL_TOTAL+ORDER_TOTAL;
		DISCOUNTED_TOTAL:=DISCOUNTED_TOTAL+DISCOUNT_TOTAL;
		TOTAL_DIF:=ORIGINAL_TOTAL-DISCOUNTED_TOTAL;
	END LOOP;
	CLOSE ORDER_CALC;
	DBMS_OUTPUT.PUT_LINE(CHR(5)||'TOTAL FOR ALL INVOICES:');
	DBMS_OUTPUT.PUT_LINE(CHR(9)||'Original Total:'||CHR(4)||TO_CHAR(ORIGINAL_TOTAL,'$999,999.99')||CHR(5)||'Discounted Total:'||
		TO_CHAR(DISCOUNTED_TOTAL,'$999,999.99')||CHR(5)||'Difference:'||CHR(4)|| TO_CHAR(TOTAL_DIF, '$999.99'));
END;
/


/*2*/
DECLARE
	ORDERNUM	ORDERS.O_ID%TYPE;
	CURSOR ORDER_CURSOR IS
		SELECT ORDERS.O_ID FROM ORDERS ORDER BY O_ID;
	CURSOR LINE_CURSOR IS
		SELECT ORDER_LINE.OL_QUANTITY "QTY", 
			INVENTORY.INV_SIZE "SIZE", 	
			INVENTORY.COLOR "COLOR", 
			ITEM.ITEM_DESC "DESC"
		FROM ORDERS, 
			ORDER_LINE, 
			INVENTORY, 
			ITEM
		WHERE ORDERS.O_ID=ORDER_LINE.O_ID 
			AND ORDER_LINE.INV_ID=INVENTORY.INV_ID 
			AND INVENTORY.ITEM_ID=ITEM.ITEM_ID
			AND ORDERS.O_ID=ORDERNUM;
	ORDER_ROW LINE_CURSOR%ROWTYPE;
BEGIN
	DBMS_OUTPUT.PUT_LINE('ALL ORDERS:');
	OPEN ORDER_CURSOR;

	LOOP
		FETCH ORDER_CURSOR INTO ORDERNUM;
		EXIT WHEN ORDER_CURSOR%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE('ORDER #'||ORDERNUM||' contains:');    
		OPEN LINE_CURSOR;	
        	LOOP
			FETCH LINE_CURSOR INTO ORDER_ROW;
			EXIT WHEN LINE_CURSOR%NOTFOUND;
        		DBMS_OUTPUT.PUT_LINE('   '||ORDER_ROW."QTY"||'   '||
				ORDER_ROW."SIZE"||'   '||ORDER_ROW."COLOR"||
				'   '||ORDER_ROW."DESC");
		END LOOP;
		CLOSE LINE_CURSOR;
	END LOOP;
	CLOSE ORDER_CURSOR;
END;
/
